"""Cycle 10: Build independent banlist per pocket.

Cycle 9 discovered: Beijing +272% at 0.10-0.15 but -80% at 0.20-0.40.
Moscow opposite. Banlists MUST be per-pocket.
"""
from pathlib import Path
import re
import numpy as np
import pandas as pd
import sys
sys.path.insert(0, '.')
from cycle9_weather_segment import load, CITY_CLIMATE

TAKER_FEE = 0.01


def per_pocket_analysis(df: pd.DataFrame):
    pockets = [
        ("S",  0.30, 0.36),
        ("A+", 0.22, 0.30),
        ("A",  0.36, 0.40),
        ("B",  0.10, 0.15),
    ]

    all_rules = {}
    for tier, lo, hi in pockets:
        sub = df[(df["p"] >= lo) & (df["p"] <= hi)].copy()
        if len(sub) < 30:
            continue
        sub["pnl"] = np.where(
            sub["yes_won"], 1/sub["p"]-1-TAKER_FEE, -1-TAKER_FEE
        )
        print(f"\n{'='*80}\nTier {tier} [{lo:.2f}-{hi:.2f}]  n={len(sub)}, mean_pnl={sub['pnl'].mean()*100:+.1f}%")
        print(f"{'='*80}")

        # City breakdown
        gc = sub.groupby("city").agg(
            n=("pnl","size"),
            mean_pnl=("pnl","mean"),
            win=("yes_won","mean"),
        )
        gc = gc[gc["n"] >= 8].copy()
        gc["mean_pnl_pct"] = (gc["mean_pnl"]*100).round(1)
        gc["win_pct"] = (gc["win"]*100).round(0)
        gc = gc.drop(columns=["mean_pnl","win"]).sort_values("mean_pnl_pct", ascending=False)

        print(f"\nCities (n>=8):")
        print(gc.to_string())

        # Auto-build banlist: cities with mean_pnl_pct < -10% and n>=10
        banned = gc[(gc["mean_pnl_pct"] < -10) & (gc["n"] >= 10)].index.tolist()
        preferred = gc[gc["mean_pnl_pct"] > 30].index.tolist()
        print(f"\nBANNED for tier {tier}: {banned}")
        print(f"PREFERRED for tier {tier}: {preferred}")

        all_rules[tier] = {
            "banned": banned,
            "preferred": preferred,
            "city_stats": gc.to_dict("index"),
        }

    # Save to file for scanner to ingest
    out = Path("data/results/cycle10_per_pocket_rules.py")
    with out.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by cycle10_per_pocket_banlist.py\n")
        f.write("# Tier → {banned: [cities], preferred: [cities]}\n\n")
        f.write("PER_POCKET_RULES = {\n")
        for tier, rules in all_rules.items():
            f.write(f"    {tier!r}: {{\n")
            f.write(f"        'banned': {rules['banned']!r},\n")
            f.write(f"        'preferred': {rules['preferred']!r},\n")
            f.write(f"    }},\n")
        f.write("}\n")
    print(f"\nSaved rules to {out}")


def main():
    df = load()
    print(f"Loaded {len(df):,} exact-bucket weather markets")
    per_pocket_analysis(df)


if __name__ == "__main__":
    main()
